data/languages.json

Hi, I noticed there is a missing entry in languages.json for Twin Vipers Wraith Blueprint, it was available at an invasion a few days ago and I took the key name directly from the world state JSON, so it is correct.
I made it consistent with this weapon's part names in languages.json ("Wraith Twin Vipers", word "Wraith" is first), although maybe it could all be changed to "Twin Vipers Wraith" as it is in the game.

Added missing language string for Twin Vipers Wraith Blueprint

---

data/cs/languages.json
data/de/languages.json
data/es/languages.json
data/fr/languages.json
data/it/languages.json
data/languages.json
data/pl/languages.json
data/pt/languages.json
data/sr/languages.json
data/tr/languages.json
data/zh/languages.json

Fixed wrong name of "Twin Grakatas Towsun Skin".
---
1. I got "https://api.warframestat.us/pc/voidTrader"
1. "https://raw.githubusercontent.com/WFCD/warframe-items/master/data/json/Skins.json" item names and comparisons were made.
1. When I did that, the "s" was missing, so I checked the game and wiki and realized it was a typo.
---
You can see my fix [on this line](#line-number-1235234) for where the new data exists
- Does this introduce opinionated data formatting or manual data entry? **[Yes]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix]**
This is my first pull …

fix: "Twin Grakatas Towsun Skin" typo

---

data/languages.json

Updated Grove Guardian NW act description (now requires only one specter to be defeated)

Grove Guardian NW act description update

---

data/languages.json

The "no life support" requirement was dropped from this challenge some time ago and the description updated to include "Kuva Fortress"
Change to drop the "life support" requirement was announced here - https://forums.warframe.com/topic/1101014-nightwave-intermission/
Change to add the Kuva Fortress to description was announced here - https://forums.warframe.com/topic/1286070-update-3090-prime-resurgence/

fix: Kuva Survival Nightwave description

---

data/languages.json

Add details for some of the new acts.
Daily:
* A Firm Shake
* Builder's Touch
* Two For One
Elite Weekly
* Antiquarian
* Terminated
Wording taken from the in-games wording, with slight modification in the cases where a count is kept track of (Antiquarian, Terminated) to match other such cases.
API strings taken from checiking the output at https://api.warframestat.us/pc

Add description for new acts.

---

data/languages.json

Add several more of the new nightwave acts
Descriptions taken from in game, with minor modifications for those that keep a count (Death from Above, Loyalty, Night and Day)
API strings taken from checiking the output at https://api.warframestat.us/pc
Death from Above
Augmentation
Topping of the Tank
Night and Day
Loyalty
Mad Lab
The Price of Freedom
I forgot to record the API string for Swatter, so that daily is not included.

feat(nightwave): more new nightwave challenges

---

data/languages.json

Several of the nightwave acts added in my last PR (#348) had the description and name entries swapped.
This fixes those and also fixes a typo in the "Builder's Touch" description.

fix: swapped nightwave descriptions

---

data/languages.json

The cold steel task has the incorrect count

Fix number for the "Cold Steel" Nightwave task

---

data/languages.json

I added the lang for the discord community title that shows up under news, might not really be important but thought I'd add it for completion sake. 
If I can figure it out I'll also add a way to parse it in the parser.
---
```json
{
"id": "62d31b87106360aa5703954d",
"message": "/Lotus/Language/CommunityMessages/JoinDiscord",
"link": "https://discord.com/invite/playwarframe",
"imageLink": "https://i.imgur.com/CNrsc7V.png",
"priority": false,
"date": "2022-07-16T20:10:00.000Z",
"eta": "65d 21h 55m 50s ago",
"update": false,
"primeAccess": false,
"stream": false,
"translations": {
"en": "/Lotus/Language/CommunityMessages/JoinDiscord",
"fr": "/Lotus/Language/CommunityMessages/JoinDiscord",
"it": "/Lotus/Language/CommunityMessages/JoinDiscord",
"de": …
```

feat: discord community lang

---

data/languages.json

The Confiscated task is now a daily task, but otherwise the description and name is unchanged.

fix: new confiscated task nightwave daily

---

data/languages.json

Adds the new Nightwave Act "Crystal Clear"

Add new nightwave act

---

data/languages.json

Further nightwave updates
- Thrill rider
-  Task renamed
- Description changed
- Hush - description updated
- Orb Valis Conservation - number changed
- PoE bounties - number changed
- Venus Fisher - number changed

fix: nightwave updates

---

data/languages.json

Adding mappings for Primed Convulsion, Combo Fury, Umbra Pedestal, Tannukai armor set, De Nas pistol skin. new Quarter's wallpaper javi's scrawling, and the wintercress Syandana.
---

feat: add new items from baro

---

data/languages.json

This fixes a bug in the initial list of permanent weeklies (entries for 'Mission Complete' and 'Not a Warning Shot' were swapped) and adds a list of entries  o handle the appended numbers DE added to the permanent weeklies:
My choice of 30 weeks is somewhat arbitrary, but it is enough to cover the all the "Nora's Mix" Nightwaves, based on the dates  from the wiki.

feat: permanent weeklies list

---

data/languages.json

Add lang strings for Gyromag, Atmo, and Repeller Systems.
---
---

feat: add lang strings for Gyromag, Atmo, and Repeller Systems

---

data/languages.json

Adds new items from Baro
---
---
- Does this contain a new dependency? **[Yes/No]**
- Does this introduce opinionated data formatting or manual data entry? **[Yes/No]**
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes/No]**
- Have I run the linter? **[Yes/No]**
- Is is a bug fix, feature request, or enhancement? **[Bug Fix/Feature/Enhancement/Docs/Maintenance]**

feat: add new Baro Ki'teer items

---

data/languages.json

Add the uppercased version of "Teshin Glyph"
---
---

fix: add new lang for Teshin glyph

---

data/languages.json

Adds Rapier Tributaker Skin lang string
---
---

fix(langs): add `Rapier Tributaker Skin`

---

tools/translation.js

Adds the umbra polarity to the polarity map
---
---

fix: add Umbra polarity to `translatePolarity`

---

package-lock.json
package.json

prepare instead of postinstall peer deps
---
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Maintenance]**

fix: move postinstall to prepare

---

data/fissureModifiers.json

Adds new Omnia T6 fissures
---
---
- Does this introduce opinionated data formatting or manual data entry? **YesNo**

feat: add new Omnia fissures

---

data/solNodes.json

Adds Yuvarium and Circulus Lua to SolNodes
---
---

fix: add missing Lua nodes

---

tools/translation.js

A typo found in polarityMap and focusMap where `Vazarin` is typed out as `Varazin`
---
---
https://github.com/WFCD/warframe-worldstate-data/blob/master/tools%2Ftranslation.js#L283
https://github.com/WFCD/warframe-worldstate-data/blob/master/tools%2Ftranslation.js#L297

fix: typo in Vazarin focus/polarity

---

tools/translation.js

Looks like DE made Dreamer's Bond to a universal polarity which shows up as AP_ANY when parsed in warframe-items. Not sure if this should be added here as well though
https://forums.warframe.com/topic/1391568-pc-dante-unbound-deep-archimedea-hotfix-3553/?ct=1712923112
> Changed the Polarity of the Dreamer’s Bond Aura Mod from Madurai to Universal, as promised in the Whispers in the Walls: 35.1 Update where it was introduced!  
---
---

fix: add the universal Aura polarity

---

data/archonShards.json

Didn't realize I left the crimson shards with `upgrades` when I switched it over to `upgradeTypes`
---
---

fix: two archon shards using `upgrades` instead of the `upgradeTypes` key

---

data/solNodes.json

Adds https://warframe.fandom.com/wiki/Armatus to solNodes
---
---

fix: add `Armatus (Deimos)`

---

data/languages.json

adds lang for `Primed Redirection` and closes https://github.com/WFCD/warframe-worldstate-parser/issues/538
---
---

feat: add lang for `Primed Redirection`

---

data/languages.json

Add event progress string for Thermia fracture 
---
---

fix: add `ScoreLocTag` for `Thermia Fracture` event

---

data/languages.json

realized that languageDesc searches for `desc` instead of `description`
---
---

fix: switched `description` to `desc` for DA data

---

data/languages.json

adds Hostile Regeneration and Fissure Cascade modifiers 
---
---
- Is is a bug fix, feature request, or enhancement? **Enhancement**

feat: more deep archimedea modifiers

---

data/languages.json

Deep Archimedea seems to be currently in sync with the in-game challenges so I managed to add some that showed up for this week
---
---
- Is is a bug fix, feature request, or enhancement? **Enhancement**

fix: updated modifiers and risk variables for DA
