WFCD/warframe-worldstate-data

data/languages.json

Add Ki'Teer Sugatra and Primed Regen

---

package.json
tools/sort_languages.py

Running sort_languages.py after adding entries to languages.json will sort them into their correct location

Add tools directory and add sort_languages.py in it

---

data/solNodes.json

SolNode404, `Striborg (Void)` should be `Stribog (Void)`

Fix typo in solNode.json

---

data/missionTypes.json
data/solNodes.json

Their values were discovered today since PoE appeared in a sortie. Screenshots of the API, the parsed API and the in-game values here https://imgur.com/a/ntyK1
It's first time attempting a pull request directly from the GitHub website. I'm not entirely sure I got everything right - haha.

Add SolNode228 and MT_LANDSCAPE to their respective files

---

data/eventsData.json
data/factionsData.json
data/fissureModifiers.json
data/languages.json
data/missionTypes.json
data/operationTypes.json
data/persistentEnemyData.json
data/solNodes.json
data/sortieData.json
data/upgradeTypes.json

- uppercase and leading whitespace removal
- unify code style across multiple JSON files
note:
no data structure was changed, these are purely cosmetic updates to have consistency

Update uppercase and leading whitespace

---

data/solNodes.json

Updated Yursa and Caracol to their new mission types.

Updated nodes to "Dark Sector Defection" mission

---

data/languages.json

lang updates

---

data/synthTargets.json

Just small changes that my small brain didn't see the first time around.

Updated synthTargets.json to remove inconsistency

---

.mergify.yml
.travis.yml

This change has been made by @TobiTenno from https://mergify.io simulator.
---
<details>
<summary>Mergify commands and options</summary>
<br />
More conditions and actions can be found in the [documention](https://doc.mergify.io/).
<br />
<br />
You can also trigger Mergify actions by commenting on this pull request:
- `@Mergifyio refresh` will re-evaluate the rules
- `@Mergifyio rebase` will rebase this PR
- `@Mergifyio backports <destination>` will backport this PR on `<destination>` branch
Additionally, on Mergify [dashboard](https://dashboard.mergify.io/) you can:
- look at your merge queues
- generate the Mergify configuration with the simulator.
Finally, you can contact us on https://mergify.io/
</details>

Mergify: configuration update

---

data/languages.json

fix(language): Scarlet Spear

---

data/solNodes.json
test/solNodes.js

Adds some missing nodes & update existing to be in line with current nodes as of U29.10

fix(solnodes): Update Railjack Nodes

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.mergify.yml

update mergify config
---
---
You can see my fix [on this line](#line-number-1235234) for where the new data exists
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Is is a bug fix, feature request, or enhancement? **[Maintenance]**

ci: update mergify config

---

data/languages.json

Updated EN localization of Polarized NW act description.

fix: Polarized NW challenge description

---

data/languages.json

Another batch of Nightwave acts
* Bloodthirsty
* Liquidation
* Medic
* Swatter
* The Old Ways

fix: Add more new acts

---

data/languages.json

Another set of nightwave acts.
* Stay on Top
* The Personal Touch
* The Many Made Whole

feat: new Nightwave acts

---

data/languages.json

Fixes incorrect api string for the Nightwave daily 'Medic'.

fix: medic lang string

---

data/languages.json

Add more of the new acts:
* Eternal Guardian
* Rise of the Machine
* Zariman Bounty Hunter

feat: nightwave acts

---

.github/workflows/ci.yaml
.github/workflows/release.yaml
.nvmrc
exports.js

- add uk locale to languages
- ci: update some actions
---
Run build, access data.locales
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[No]**
- Is is a bug fix, feature request, or enhancement? **[Maintenance]**

fix(i18n): add uk locale

---

data/languages.json

Add the new 'Archon Hunter' act

fix(nightwave): Add 'Archon Hunter' Elite Weekly act

---

data/languages.json

fix: friendly fire weekly

---

data/languages.json

Added `Altra Sentinel Mask` under lang
---
---

fix(lang): add `Altra Sentinel Mask`

---

data/archonShards.json
exports.js
test/archonShards.spec.js
test/utilities/translation.spec.js
tools/translation.js

Adds archon shard data including upgrade types. Thanks @Sainan 
---
---

feat: add archon shards data

---

data/archonShards.json

Remove trailing spaces from some of the values
---
---
- Is is a bug fix, feature request, or enhancement? **Maintenance**

style: remove some trailing space in values

---

data/syndicatesData.json

Add Cavia syndicate data
---
---

feat: add Cavia syndicate name

---

data/languages.json
data/missionTypes.json
data/solNodes.json
test/solNodes.spec.js

Adds language strings for motes and event name. Still not sure where to find the event short description so opted not to add
---
---

feat: add some lang strings for `Operation: Belly of the Beast`

---

data/factionsData.json

add mitw
---
nah
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
- Have I run the linter? **[No]**
- Is is a bug fix, feature request, or enhancement? **[Enhancement]**

feat: add MITW faction

---

data/factionsData.json
tools/translation.js

Added Narmer faction unique string
---
---

feat(factions): add narmer

---

data/languages.json

closes #551
---
---
- Does this pr include updated data files in a separate commit that can be reverted for a clean code-only pr? **[Yes]**
- Is is a bug fix, feature request, or enhancement? **[Maintenance]**

fix: corrupted damage mods -> orokin

---

data/languages.json

Added more modifiers that were obvious when reading them from the wikia (and a typo)
---
---
- Is is a bug fix, feature request, or enhancement? **Enhancement**

feat: added more DA personal modifiers

---

data/languages.json

Add Conquera Kuaka Floof lang
---
---

feat: add Conquera Kuaka Floof

---

data/languages.json
data/solNodes.json

add event langs and hub for Star days
---
---
- Is is a bug fix, feature request, or enhancement? **Enhancement**

feat: add event langs for star days
